version: "3"
services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #  - "8080:8080"
    volumes:
     - .:/usr/src/app
    tty: true
    # command: 
    #   - go 
    #   - run 
    #   - server.go
